export const clubNames = [
  "Red Lions",
  "Blue Stars",
  "White Tigers",
  "Green Dragons",
  "Black Bears",
  "Yellow Eagles",
  "Purple Panthers",
  "Orange Wolves",
  "Gray Falcons",
  "Pink Jaguars",
  "Sky Sharks",
  "Crimson Hawks",
  "Golden Tigers",
  "Silver Sharks",
  "Emerald Lions",
  "Azure Falcons",
  "Violet Panthers",
  "Cobalt Wolves",
  "Bronze Bears",
  "Maroon Tigers",
  "Indigo Lions",
  "Ruby Dragons",
  "Ivory Eagles",
  "Sapphire Hawks",
  "Copper Dragons",
  "Teal Tigers",
  "Coral Sharks",
  "Pearl Eagles",
  "Platinum Lions",
  "Cinnamon Falcons",
  "Magenta Hawks",
  "Lime Dragons",
  "Aqua Tigers",
  "Amber Eagles",
  "Olive Panthers",
  "Onyx Sharks",
  "Peach Falcons",
  "Periwinkle Lions",
  "Scarlet Tigers",
  "Turquoise Sharks",
  "Topaz Falcons",
  "Tangerine Lions",
  "Tawny Tigers",
  "Thistle Panthers",
  "Wisteria Hawks",
  "Walnut Wolves",
  "Wheat Bears",
  "Apricot Lions",
  "Aquamarine Eagles",
  "Beige Sharks",
  "Burgundy Tigers",
  "Burnt Bears",
  "Celadon Dragons",
  "Chartreuse Lions",
  "Coal Sharks",
  "Copper Falcons",
  "Crimson Tigers",
  "Fuchsia Hawks",
  "Goldfish Dragons",
  "Hickory Lions",
  "Honey Eagles",
  "Jade Panthers",
  "Jet Sharks",
  "Lavender Tigers",
  "Lemon Lions",
  "Mauve Falcons",
  "Mint Sharks",
  "Mustard Dragons",
  "Obsidian Eagles",
  "Olive Bears",
  "Pumpkin Panthers",
  "Pineapple Lions",
  "Quartz Dragons",
  "Royal Sharks",
  "Rusty Falcons",
  "Sable Tigers",
  "Sepia Panthers",
  "Slate Hawks",
  "Sunflower Lions",
  "Tangelo Eagles",
  "Vanilla Panthers",
  "Velvet Sharks",
  "Wine Dragons",
  "Zinc Bears",
];

function shuffleArray(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}

const footballClubs = shuffleArray(clubNames);
export default footballClubs;
